In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [3]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [4]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  57129.477 
Prediction:
 [-51.424164 -76.4257   -67.63683  -75.01459  -60.853832]
10 Cost:  41.71131 
Prediction:
 [159.91328 177.6332  182.66728 197.563   132.93858]
20 Cost:  40.967094 
Prediction:
 [160.52794 178.41888 183.41704 198.38216 133.54732]
30 Cost:  40.746895 
Prediction:
 [160.50511 178.43819 183.41174 198.37909 133.57147]
40 Cost:  40.527657 
Prediction:
 [160.4804  178.45515 183.40417 198.3735  133.5938 ]
50 Cost:  40.309765 
Prediction:
 [160.45575 178.47206 183.39665 198.368   133.61606]
60 Cost:  40.092957 
Prediction:
 [160.4312  178.48895 183.38914 198.36246 133.63828]
70 Cost:  39.877277 
Prediction:
 [160.40665 178.50575 183.38162 198.35693 133.6604 ]
80 Cost:  39.66286 
Prediction:
 [160.38222 178.52252 183.37415 198.35144 133.6825 ]
90 Cost:  39.449593 
Prediction:
 [160.35783 178.53925 183.3667  198.34595 133.70451]
100 Cost:  39.23744 
Prediction:
 [160.33351 178.55591 183.35925 198.34048 133.72649]
110 Cost:  39.02645 
Prediction:
 [160.30927 178.572

사실 위의 방법은 식이 길어지면 너무 코드도 길어지고 스파게티 코드가 되버리기때문에
이런식으로 구현하지는 않는다

Matrix를 이용해야된다

In [5]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])   # shape 부분이 중요, Matrix의 row/column에 맞게 잘 조정
Y = tf.placeholder(tf.float32, shape=[None, 1])   # None은 식에서 총 train data의 개수를 의미 = n

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  11971.714 
Prediction:
 [[37.684696]
 [80.0701  ]
 [60.625134]
 [70.49924 ]
 [65.977005]]
10 Cost:  123.74687 
Prediction:
 [[134.01476]
 [195.77011]
 [174.66881]
 [194.68431]
 [154.21136]]
20 Cost:  122.98334 
Prediction:
 [[134.34917]
 [196.09079]
 [175.02713]
 [195.06891]
 [154.44037]]
30 Cost:  122.33179 
Prediction:
 [[134.39307]
 [196.06248]
 [175.04147]
 [195.0789 ]
 [154.40326]]
40 Cost:  121.68363 
Prediction:
 [[134.43594]
 [196.03316]
 [175.05469]
 [195.08772]
 [154.3654 ]]
50 Cost:  121.03906 
Prediction:
 [[134.47868]
 [196.00389]
 [175.06787]
 [195.09653]
 [154.32765]]
60 Cost:  120.39795 
Prediction:
 [[134.52133]
 [195.97473]
 [175.08102]
 [195.10527]
 [154.29001]]
70 Cost:  119.76044 
Prediction:
 [[134.56387]
 [195.94568]
 [175.09418]
 [195.11407]
 [154.2525 ]]
80 Cost:  119.12622 
Prediction:
 [[134.60626]
 [195.91666]
 [175.10727]
 [195.12279]
 [154.21504]]
90 Cost:  118.495384 
Prediction:
 [[134.64857]
 [195.88773]
 [175.12029]
 [195.13147]
 [154.1777 ]]
